version: "2"
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020  # Expose the HDFS port for spark (yarn)
    networks:
      - hadoop-network
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

  # ici, le seul datanode est public expose le port 9864 for data transfert (HdfsCLI)
  # son hostname est necessaires à la resolution @ip lors d'un appel au datanode par appli externe
  datanode:            
    image: apache/hadoop:3
    hostname: datanode
    command: ["hdfs", "datanode"]
    ports:
      - 9864:9864     
    networks:
      - hadoop-network
    env_file:
      - ./config
  
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    networks:
      - hadoop-network
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
      - ./tmp:/opt/tmp

  nodemanager:
    image: apache/hadoop:3
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    networks:
      - hadoop-network
    env_file:
      - ./config

networks:
  hadoop-network:
    driver: bridge
